defaults:
  - _self_
  - datamodule: ventilator_datamodule_0
  - trainer: default_trainer
  - training: default_training
#  - logging: wandb
  - logging: loggers
  - optimizer: adam
  - scheduler: exponential
  - model: ventilator_model__0
  - callbacks: callbacks
  - private: default
  - loss: mae
  - metric: metric_manager
  - inference: basic
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  logs_folder_name: logs
  workspace: erlemar
  project_name: ventilator_kaggle_new
  device: cuda
  log_code: False
  save_pytorch_model: True
  save_best: True
  convert_to_jit: False
  predict: True

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S} #_${hydra.job.override_dirname}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
