lr: 0.001
#metric: ${metric.metric.metric_name}
metric: ${metric.metric.metric_name}_epoch
#metric: 'ds'
mode: "min"
seed: 2021
debug: False
n_classes: 1
lightning_module_name: src.lightning_classes.lightning_ventilator.VentilatorRegression
loss_calc_style: 1
pp_for_loss: False