path: d:/DataScience/Python_projects/Current_projects/GBVPP/data
split: GroupKFold
n_folds: 5
fold_n: 0
class_name: src.datasets.ventilator_dataset2_post.VentilatorDataset
data_module_name: src.lightning_classes.datamodule_ventilator_0_post.VentilatorDataModule
num_workers: 0
batch_size: 256
pin_memory: True
train_len: 6036000
normalize: True
normalize_all: False
make_features_style: 1
use_lag: 4
top_n: False